# Generated by Django 5.2.13 on 2026-04-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=8, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('picture', models.ImageField(upload_to='guide_pics/')),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('living_place', models.CharField(max_length=255)),
                ('locations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_name', models.CharField(max_length=255)),
                ('tourist_phone_number', models.CharField(max_length=15)),
                ('tour_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='guides.guide')),
            ],
        ),
    ]
